application: gae-php-hybridauth
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:

- url: /images
  static_dir: images

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
      
- url: /auth
  script: auth.php

- url: /logout
  script: logout.php

- url: .*
  script: main.php
